### ISSUE TITLE
Double click on mention list

### ISSUE THREAD

**Issue by abderrahmane-tj** [lyricat/Hotot#485]
I like Hotot very mush, therefor I feel the need to contribute, even by reporting this issue : when you double click on the list that shows up when you try to mention someone, two times the username you clicked on gets appended to the tweet's text. 

I am using Hotot on Ubuntu.

**Comment by lyricat** [comment]
@abderrahmane-tj thank you for the report. but i didn't use Hotot for a long time...

**Comment by atahrijouti** [comment]
@lyricat me neither 🙈

**Comment by lyricat** [comment]
yea... what's a pity
