### ISSUE TITLE
user names prepended with '.' at start of tweet not clickable

### ISSUE THREAD

**Issue by grrrrr** [lyricat/Hotot#516]
Ubuntu 12.04.2
Hotot 0.9.7.32

if addressing a tweet to a user but you want your follower to see it in all clients the common practice is to prepend a period to the @username

expected behavior:
If a tweet starts with ".@someuser" the "someuser" should be a link to some users profile.

actual behavior:
If a tweet starts with ".@someuser" the "someuser" is presented as plain text and not a link to the profile.

**Comment by Volvagia356** [comment]
Appears to have been fixed in the latest version
